# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' lasvmTrain
#' 
#' Use lasvm to train a given problem.
#'
#'  @param	x		data matrix 
#'  @param	rounds		number of rounds (orthogonal views)
#'  @param	k		number of clusters
#'  @param	iter	numer of iterations in one round
#'  @param	initType		centroid initialization via Random or KMeans++
#'  @param	verbose		verbose output?
#'
#'  @return	a list consisting of
#'	centers	these are the resulting centroids of the kmean algorithm (as a std::vector of NumericMatrix)
#'	cluster 	these are the labels for the resulting clustering (as a std::vector of NumericVector)
#'	obj			this is a vector with the final objective value for each round
#'
lasvmTrain <- function(x, y, gamma, cost, degree = 3L, coef0 = 0L, optimizer = 1L, kernel = 2L, selection = 0L, termination = 0L, cachesize = 256L, bias = 1L, epochs = 1L, epsilon = 0.001, verbose = FALSE) {
    .Call('lasvmR_lasvmTrain', PACKAGE = 'lasvmR', x, y, gamma, cost, degree, coef0, optimizer, kernel, selection, termination, cachesize, bias, epochs, epsilon, verbose)
}

